feat(EquipList): change equips render method
MooncellWiki/prts-widgets pull request #107
Opened 2024-04-18 08:57 UTC by ZSLNAAKII

2024-04-19 04:50 UTC, daflyinbed requested changes

2024-04-19 04:50 UTC, daflyinbed commented on src/widgets/EquipList/EquipTable.vue
> +          const rawdata = (v ?? {}) as DOMStringMap[];
还有这里

2024-04-19 04:50 UTC, daflyinbed commented on src/widgets/EquipList/index.vue
> +
都用ref吧 最好不要reactive和ref混着用

2024-04-19 07:24 UTC, ZSLNAAKII commented
另外，我想问一下可否将模组数据加入Cargo表格中？就不必逐个获取了

2024-04-20 07:07 UTC, daflyinbed commented
> 另外，我想问一下可否将模组数据加入Cargo表格中？就不必逐个获取了

看了眼 模组有往cargo存啊 https://prts.wiki/w/%E7%89%B9%E6%AE%8A:CargoTables/char_mod 你看要是缺什么就加什么呗

2024-04-20 07:08 UTC, daflyinbed approved these changes

2024-04-20 08:39 UTC, ZSLNAAKII commented
好的，现在已经添加，需要重新创建数据，还请重新创建一下

2024-04-20 10:47 UTC, daflyinbed commented
> 好的，现在已经添加，需要重新创建数据，还请重新创建一下

回滚了 重建的时候报错
round(): Argument #1 ($num) must be of type int|float, string given

2024-04-20 10:58 UTC, StarHeartHunt approved these changes

2024-04-20 10:58 UTC, StarHeartHunt commented on src/widgets/EquipList/Equip.vue
> +              style="height: 30px"
```suggestion
              height="30"
```

2024-04-22 07:27 UTC, StarHeartHunt approved these changes

2024-04-22 07:27 UTC, merged

2024-04-29 00:42 UTC, StarHeartHunt commented
```
[plugin:vite:esbuild] [plugin vite:esbuild] src/widgets/EquipList/Equip.vue?vue&type=script&lang.ts: The "??" operator here will always return the left operand
25 |  
26 |  function getStatColor(type: string, stat: string): string {
27 |    return Number(stat) * statsStyleMap[type] ?? 1 >= 0 ? "#00B0FF" : "#FF6237";
   |                                              ^
28 |  }
29 |  
```

这个是在干什么

2024-04-29 01:55 UTC, ZSLNAAKII commented
这里应该是
`return Number(stat) * (statsStyleMap[type] ?? 1) >= 0 ? "#00B0FF" : "#FF6237";`
排查的时候不慎遗漏了，非常抱歉