feat(EquipList): add sort and filter for list view
MooncellWiki/prts-widgets pull request #120
Opened 2024-05-19 04:04 UTC by ZSLNAAKII

2024-05-21 14:40 UTC, RiESAEX commented on src/widgets/EquipList/equipData.ts
> +let got = false;
这cache有必要吗 请求不会走到memory cache上吗

2024-05-21 15:13 UTC, daflyinbed requested changes

2024-05-21 15:13 UTC, daflyinbed commented on src/widgets/EquipList/index.vue
> +        }
这不需要else吧 前面都return了 每个单独if就行了吧

2024-05-21 15:13 UTC, daflyinbed commented on src/widgets/EquipList/EquipTable.vue
>    <NDataTable
直接用datatable的pagination呗

2024-05-21 15:13 UTC, daflyinbed commented on src/widgets/EquipList/SubAvatar.vue
>          "
这单独抽个函数出去吧

2024-05-21 15:13 UTC, daflyinbed commented on src/widgets/EquipList/EquipTable.vue
> +    const equipList = useVModel(props, "data", emit);
我看你也没改equipList啊 当时为什么要搞着双向绑定来着

2024-05-24 14:09 UTC, daflyinbed approved these changes

2024-05-24 14:09 UTC, merged