Refactor: vue setup
MooncellWiki/prts-widgets pull request #122
Opened 2024-05-25 08:53 UTC by daflyinbed

2024-05-25 12:26 UTC, StarHeartHunt requested changes

2024-05-25 12:26 UTC, StarHeartHunt commented on src/components/CheckboxGroup.vue
> +<script lang="ts" setup>
```suggestion
<script setup lang="ts">
```

2024-05-25 12:28 UTC, daflyinbed commented on src/components/CheckboxGroup.vue
> +<script lang="ts" setup>
这顺序 eslint和prettier有规则控制吗

2024-05-25 19:23 UTC, daflyinbed commented on src/components/CheckboxGroup.vue
> +<script lang="ts" setup>
https://github.com/vuejs/eslint-plugin-vue/issues/1970

2024-05-26 00:10 UTC, StarHeartHunt commented on src/components/CheckboxGroup.vue
> +<script lang="ts" setup>
直接全部替换一下得了

2024-05-26 08:24 UTC, daflyinbed commented
@Yanstory @ZheiZhei @ZSLNAAKII @Garan902 帮忙本地试一下这个分支的有没有问题 我大致试了一下没问题 但是我不完全清楚预期的行为是什么样的 没问题的给个approve

2024-05-26 08:43 UTC, Garan902 commented
> @Yanstory @ZheiZhei @ZSLNAAKII @Garan902帮忙本地试一下这个修改的有没有问题 我大致试了一下没问题 但是我不完全清楚理想的行为是什么样的没问题的给个批准

我觉得颜色换成蓝的比较好（

2024-05-26 12:17 UTC, ZSLNAAKII commented
![屏幕截图 2024-05-26 195712](https://github.com/MooncellWiki/prts-widgets/assets/142195577/027c5fbf-85a7-458e-8f81-4601324df92c)
![屏幕截图 2024-05-26 200848](https://github.com/MooncellWiki/prts-widgets/assets/142195577/e4f241a1-6101-4f16-a97b-2969bf0b2178)

在其他widget内启用暗色主题的情况下，CVList的标签栏和标题的文字会显示为白色，桌面端虽然标题显示正常，但是标签栏依然显示为白色。这个问题现在站里用的版本也存在，倒不是因为重构产生的问题。

2024-05-26 13:19 UTC, StarHeartHunt commented
> ![屏幕截图 2024-05-26 195712](https://private-user-images.githubusercontent.com/142195577/333877062-027c5fbf-85a7-458e-8f81-4601324df92c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Mjk2NzQsIm5iZiI6MTcxNjcyOTM3NCwicGF0aCI6Ii8xNDIxOTU1NzcvMzMzODc3MDYyLTAyN2M1ZmJmLTg1YTctNDU4ZS04ZjgxLTQ2MDEzMjRkZjkyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxMzE2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzRjNDRhMWYyNmY3YTdmMTEzZmNhMDMzODE0NTJmYzYyNGIxOThhNTM5M2EyYzE1N2ExOTAxNTFiNWYwOGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ShyqaaWn-6OhvULKyX-p5ll2GhYyKf2KX8p9b-MzUas) ![屏幕截图 2024-05-26 200848](https://private-user-images.githubusercontent.com/142195577/333877684-e4f241a1-6101-4f16-a97b-2969bf0b2178.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Mjk2NzQsIm5iZiI6MTcxNjcyOTM3NCwicGF0aCI6Ii8xNDIxOTU1NzcvMzMzODc3Njg0LWU0ZjI0MWExLTYxMDEtNGYxNi1hOTdiLTI5NjliZjBiMjE3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxMzE2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTM1ODU2Njk5NWNiNjJiMDBhZDM0MTk4MGU0ZDEyYjliODlmYzY0YjdmMWRmYzRiZTE1ZGIyNDg3YTI2MjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kZDBVg6i67OC5UXd1hVSlp8zVfitNAxbqYlzZ2p_B1o)
> 
> 在其他widget内启用暗色主题的情况下，CVList的标签栏和标题的文字会显示为白色，桌面端虽然标题显示正常，但是标签栏依然显示为白色。这个问题现在站里用的版本也存在，倒不是因为重构产生的问题。

合了之后再开个 pr 改，现在只看有没有 regression

2024-05-26 13:24 UTC, ZSLNAAKII commented
> > ![屏幕截图 2024-05-26 195712](https://private-user-images.githubusercontent.com/142195577/333877062-027c5fbf-85a7-458e-8f81-4601324df92c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Mjk2NzQsIm5iZiI6MTcxNjcyOTM3NCwicGF0aCI6Ii8xNDIxOTU1NzcvMzMzODc3MDYyLTAyN2M1ZmJmLTg1YTctNDU4ZS04ZjgxLTQ2MDEzMjRkZjkyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxMzE2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzRjNDRhMWYyNmY3YTdmMTEzZmNhMDMzODE0NTJmYzYyNGIxOThhNTM5M2EyYzE1N2ExOTAxNTFiNWYwOGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ShyqaaWn-6OhvULKyX-p5ll2GhYyKf2KX8p9b-MzUas) ![屏幕截图 2024-05-26 200848](https://private-user-images.githubusercontent.com/142195577/333877684-e4f241a1-6101-4f16-a97b-2969bf0b2178.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Mjk2NzQsIm5iZiI6MTcxNjcyOTM3NCwicGF0aCI6Ii8xNDIxOTU1NzcvMzMzODc3Njg0LWU0ZjI0MWExLTYxMDEtNGYxNi1hOTdiLTI5NjliZjBiMjE3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxMzE2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTM1ODU2Njk5NWNiNjJiMDBhZDM0MTk4MGU0ZDEyYjliODlmYzY0YjdmMWRmYzRiZTE1ZGIyNDg3YTI2MjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kZDBVg6i67OC5UXd1hVSlp8zVfitNAxbqYlzZ2p_B1o)
> > 在其他widget内启用暗色主题的情况下，CVList的标签栏和标题的文字会显示为白色，桌面端虽然标题显示正常，但是标签栏依然显示为白色。这个问题现在站里用的版本也存在，倒不是因为重构产生的问题。
> 
> 合了之后再开个 pr 改，现在只看有没有 regression

其他的目前暂时没有发现什么问题

2024-05-26 13:25 UTC, StarHeartHunt approved these changes

2024-05-27 01:29 UTC, merged