add EquipList widget
MooncellWiki/prts-widgets pull request #38
Opened 2023-08-17 15:40 UTC by ZSLNAAKII

2023-08-17 17:16 UTC, daflyinbed commented
这个 以后可以换成全在前端渲染吗 给你搓个api

2023-08-17 17:42 UTC, ZSLNAAKII commented
目前这样实现是想保持和干员页的模组的样式一致，如果要在前端渲染的话，我可以试着做一下

2023-08-18 14:30 UTC, daflyinbed submitted a review, later dismissed

2023-08-18 14:31 UTC, daflyinbed commented
@ZSLNAAKII 看看有没有啥问题

2023-08-18 15:45 UTC, StarHeartHunt requested changes

2023-08-18 15:45 UTC, StarHeartHunt commented on src/widgets/EquipList/index.vue
> +            v-if="Object.keys(filteredCharData).length < 1"
```suggestion
            v-if="Object.keys(filteredCharData).length == 0"
```

2023-08-18 16:03 UTC, StarHeartHunt approved these changes

2023-08-18 16:05 UTC, merged