XbMapViewer: Init
MooncellWiki/prts-widgets pull request #5
Opened 2023-02-04 14:10 UTC by ZheiZhei

2023-02-05 11:23 UTC, daflyinbed commented
这ci估计是一时半会儿修不好了 以后再说吧

2023-02-05 11:24 UTC, daflyinbed approved these changes

2023-02-06 03:27 UTC, StarHeartHunt requested changes

2023-02-06 03:27 UTC, StarHeartHunt commented on src/widgets/XbMapViewer/Block.vue
> +      <i v-if="tile === 'start'" class="fas fa-exclamation-triangle"></i>
这堆 if 换成 object 直接查吧，估计快点

2023-02-07 07:58 UTC, merged