XbMapViewer: block style update; ISEvent: create anchor point
MooncellWiki/prts-widgets pull request #7
Opened 2023-02-10 14:32 UTC by ZheiZhei

2023-02-11 07:08 UTC, StarHeartHunt requested changes

2023-02-11 07:08 UTC, StarHeartHunt commented on src/widgets/ISEvents/ISEventFramework.vue
> +    <span :id="sceneData[0].etype"></span>
```suggestion
    <span :id="sceneData[0].etype"/>
```

2023-02-11 07:08 UTC, StarHeartHunt commented on src/widgets/ISEvents/ISEventFramework.vue
> +    <span :id="sceneData[0].name"></span>
```suggestion
    <span :id="sceneData[0].name"/>
```

2023-02-12 07:13 UTC, daflyinbed approved these changes

2023-02-12 07:19 UTC, StarHeartHunt approved these changes

2023-02-12 07:20 UTC, merged